import markdown
from xhtml2pdf import pisa
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import os
import io

def generate_pdf_from_markdown(markdown_text: str) -> bytes:
    """
    Converts Markdown text to PDF bytes.
    """
    # 1. Convert Markdown to HTML
    html_content = markdown.markdown(markdown_text)
    
    # 2. Add some basic styling
    styled_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; font-size: 12px; line-height: 1.5; color: #333; }}
            h1 {{ color: #000; font-size: 24px; border-bottom: 2px solid #000; padding-bottom: 10px; margin-top: 20px; }}
            h2 {{ color: #333; font-size: 18px; margin-top: 15px; border-bottom: 1px solid #ccc; }}
            h3 {{ color: #555; font-size: 14px; margin-top: 10px; font-weight: bold; }}
            ul {{ margin-left: 20px; }}
            li {{ margin-bottom: 5px; }}
            strong {{ color: #000; }}
            p {{ margin-bottom: 10px; }}
        </style>
    </head>
    <body>
        <h1>Executive Churn Report</h1>
        {html_content}
        <br/><br/>
        <hr/>
        <p style="font-size: 10px; color: #777;">Generated by Persona AI - Retention Intelligence Engine</p>
    </body>
    </html>
    """
    
    # 3. Convert HTML to PDF
    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(
        src=io.StringIO(styled_html),
        dest=pdf_buffer
    )
    
    if pisa_status.err:
        raise Exception("PDF generation failed")
        
    return pdf_buffer.getvalue()

def send_email_with_pdf(to_email: str, pdf_bytes: bytes, report_filename="Executive_Report.pdf") -> bool:
    """
    Sends an email with the PDF attachment using SMTP.
    Requires EMAIL_USER and EMAIL_PASSWORD env vars.
    """
    smtp_server = "smtp.gmail.com"
    smtp_port = 587
    sender_email = os.getenv("EMAIL_USER")
    sender_password = os.getenv("EMAIL_PASSWORD")
    
    if not sender_email or not sender_password:
        print("WARNING: Email credentials not set. Skipping email send.")
        print(f"Mock Success: Email would be sent to {to_email}")
        return True # Mock success for development if no creds

    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = to_email
        msg['Subject'] = "Your Executive Churn Report - Persona AI"
        
        body = "Please find attached your AI-generated executive churn report.\n\nBest,\nPersona AI Team"
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach PDF
        pdf_attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
        pdf_attachment.add_header('Content-Disposition', 'attachment', filename=report_filename)
        msg.attach(pdf_attachment)
        
        # Send Email
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
            
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False
